backend:
  name: github
  repo: BlueChili/LigaKarateBogota # Path to your Github repository
  branch: cmstest # Branch to update (master by default)

media_folder: "static/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit

  - name: "news" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Noticias" # Used in the UI, e.g., "New Post"
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción corta", name: "description", widget: "string"}
      - {label: "Imagen de portada", name: "coverImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime", format: "Y-MM-DDThh:mm:ssZ"}
      - {label: "section", name: "section", widget: "hidden", default:"news"}


  - name: "results"
    label: "Resultados"
    folder: "content/results"
    create: true
    fields:
      - {Label: "Section", name: "section", widget: "hidden", default: "results" }
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime", format: "Y-MM-DDThh:mm:ssZ"}
      - label: "Tablas"
        name: "tablas"
        widget: "list"
        required: false
        fields:
          - label: "Tabla"
            name: "tabla"
            widget: object
            fields:
            - label: "Título de la tabla"
              name: "heading"
              widget: "string"
            - label: "Columnas"
              name: "columnas"
              widget: "list"
              fields:
                - label: "Columna"
                  name: "columna"
                  widget: "object"
                  fields:
                  - {label: "Nombre", name: "heading", widget: "string"}
                  - label: "Items"
                    name: "items"
                    widget: "list"
                    fields:
                      - {label: "Item", name: "item", widget: "string"}
      - label: "Listas"
        name: "listas"
        widget: "list"
        required: false
        fields:
          - label: "Lista"
            name: "lista"
            widget: object
            fields:
            - label: "Encabezado"
              name: "heading"
              widget: "string"
            - label: "Items"
              name: "items"
              widget: "list"
              fields:
                - label: "Item"
                  name: "item"
                  widget: "object"
                  fields:
                    - {label: "Nombre", name: "name", widget: "string"}
                    - {label: "Archivo", name: "attachment", widget: "file", required: false}
      - {label: "Cuerpo", name: body, widget: markdown, required: false}

  - name: "selfHosted"
    label: "Galerías"
    folder: "content/albums"
    create: true
    fields:
      - {name: "title", label: "Título", widget: "string"}
      - {name: "date", label: "Fecha de pubicación", widget: "datetime", format: "Y-MM-DDThh:mm:ssZ"}
      - {name: "galleryType", widget: "hidden", default: "images"}
      - {name: "section", widget: "hidden", default: "galerias"}
      - name: "images"
        label: "Imágenes"
        widget: list
        fields:
          - name: "image"
            label: "Imagen"
            widget: "object"
            fields:
              - {name: "file", label: "Archivo", widget: "image"}
              - {name: "description", label: "Descripción", widget: "string", required: false}
      - {name: "body", widget: "markdown"}

  - name: "clubesdeportivos"
    label: "Clubes" # Used in the UI, e.g., "New Post"
    folder: "content/clubs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "club-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Nombre", name: "nombre", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image", required: false}
      - {label: "Dirección", name: "address", widget: "string", default: "-"}
      - {label: "Teléfono", name: "phone", widget: "string", default: "-"}
      - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Correo electrónico", name: "email", widget: "string", required: false}
      - {label: "Facebook", name: "facebook", widget: "string", required: false}
      - {label: "Twitter", name: "twitter", widget: "string", required: false}

  - name: "facebookAlbums" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Facebook albums" # Used in the UI, e.g., "New Post"
    folder: "content/galerias" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter:
      field: galleryType
      value: image
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "galleryURL", widget: "string"}
      - {label: "Imagen de portada", name: "galleryThumbnail", widget: "image", required: false}
      - { name: "galleryType", widget: "hidden", default: "image"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime", format: "Y-MM-DDThh:mm:ssZ"}


  - name: "youtube" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Youtube" # Used in the UI, e.g., "New Post"
    folder: "content/galerias" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter:
      field: galleryType
      value: video
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "galleryURL", widget: "string"}
      - {label: "Tipo de galería", name: "galleryType", widget: "hidden", default: "video"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime", format: "Y-MM-DDThh:mm:ssZ"}

