backend:
  name: github
  repo: BlueChili/LigaKarateBogota # Path to your Github repository
  branch: cmstest # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Noticias" # Used in the UI, e.g., "New Post"
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "galerias" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Galerías" # Used in the UI, e.g., "New Post"
    folder: "content/galerias" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
